### ISSUE TITLE
Create dynamic daily questionnaire page

### ISSUE THREAD

**Issue by barelmas245** [covid-diagnostics/covid-mobile-android#37]
A page with simple questions which the user should answer on every use.
We get the questions from the BE (GET /api/question) in order to support dynamic question which we can change without upgrading the app.

Each question has different type (checkbox, textbox etc) and possibly extraData which may be used differently according to the question type (for example: options of a dropdown would be in the extraData field).
(see more in the swagger doc)
https://tnj0200iy8.execute-api.eu-west-1.amazonaws.com/staging/swagger/

**Comment by svechinsky** [comment]
The initial dynamic structure is in review.
For the next stage, this needs to implement the [screens from figma](https://www.figma.com/file/bnnHW8Lx4HCTpURSz2YJ9z/%D7%90%D7%A4?node-id=390%3A2669
)

ATM the screens are missing the general feeling question and don't show the proper flow for the covid test question.
- The general feeling question allows 3 possible outputs [SAME, BETTER,WORSE] and should be required.

- The covid test question should first ask the user if they performed a test, then if it's positive or negative and only then the date of the test. Accordingly it should the the positiveTestDate and negativeTestDate if applicable
