### ISSUE TITLE
Fix constrains - for smaller screens

### ISSUE THREAD

**Issue by barelmas245** [covid-diagnostics/covid-mobile-android#46]
The app should look better on smaller screen.
BLOCKED for now because of all the UI changes which are already in progres, so just need to take it into consideration.

**Comment by YuvCoh** [comment]
![cren](https://user-images.githubusercontent.com/4635728/80817120-7ed0d200-8bd9-11ea-85f2-5fff0d5dfb68.jpeg)

Unusable on my s7.

Can be temporarily "patched" by placing it in a scrollview until properly solved.
